{
    "name": "MySM - Inventory",
    "version": "15.0.0.1.0",
    "author": "Port Cities",
    "website": "https://www.portcities.net",
    "summary": "Inventory Customization",
    "description":
    """
    - Inventory Customization
    """,
    "depends": [
        "product",
        "purchase",
        "stock",
        "uom",
        "website_sale"
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/uom_data.xml",
        "data/ir_sequence_data.xml",
        "views/account_move_views.xml",
        "views/res_company_view.xml",
        "views/res_partner_bank_view.xml",
        "views/mysm_attribute_views.xml",
        "views/product_views.xml",
        "views/mysm_contact_views.xml",
        "views/mysm_allergen_composition_view.xml",
        "views/mysm_allergen_view.xml",
        "views/purchase_order_view.xml",
        "views/product_ribbon_views.xml",
        "views/stock_location_views.xml",
        "views/stock_production_lot_views.xml",
        "views/mysm_stock_menuitem.xml",
        "views/stock_move_views.xml",
        "wizard/generate_pif_report_wizard_views.xml",
        "report/product_pif_report.xml",
        "report/product_batch_label_report.xml",
        "report/mo_pif_report.xml",
        "report/paper_format.xml",
        "report/purchase_order_report_template.xml",
        "report/customer_invoice_report_template.xml",
        "report/stock_location_report_template.xml",
    ],
    "sequence": 1,
    "active": True,
    "installable": True,
    "auto_install": False,
    "application": False,
    "license": "AGPL-3",
}
