from . import mysm_attribute
from . import product
from . import res_config_settings
from . import mysm_allergen
from . import mysm_allergen_composition
from . import stock_production_lot
from . import mrp_bom
from . import mrp_production
from . import purchase_order
from . import account_move
from . import res_company
from . import res_partner_bank
from . import stock_location
from . import product_ribbon
from . import stock_move